version: "3.9"
services:
  zic-gui:
    container_name: zic-gui
    depends_on:
      - zic
    ports:
      - "80"
    expose:
      - 80
    restart: always
    labels:
      - traefik.enable=true
      - traefik.http.services.zic-gui.loadbalancer.server.port=80
      - traefik.http.routers.zic-gui.tls=true
      - traefik.http.routers.zic-gui.entrypoints=websecure
      - traefik.http.routers.zic-gui.rule=(PathPrefix(`/`))
      - traefik.http.routers.zic-gui.service=zic-gui
  zic:    
    container_name: zic
    ports:
      - "8081"
    expose:
      - 8081
    restart: always
    environment:
      - ASPNETCORE_URLS=http://+:8081
      - LOG_PATH=/logs/
      - ZKEYCLOAK_URL=http://zkeycloak:8080/auth
      - CONFIG_PATH=/config/config.json
    labels:
      - traefik.enable=true
      - traefik.http.services.zic.loadbalancer.server.port=8081
      - traefik.http.routers.zic.tls=true
      - traefik.http.routers.zic.entrypoints=websecure
      - traefik.http.routers.zic.rule=(PathPrefix(`/zic`))
      - traefik.http.routers.zic.service=zic
      - traefik.http.routers.zic.middlewares=zic
      - traefik.http.middlewares.zic.chain.middlewares=zic-strip-prefix
      - traefik.http.middlewares.zic-strip-prefix.stripprefix.prefixes=/zic
    volumes:
      - /opt/zerto/zic/config/:/config/
      - /opt/zerto/zic/logs/:/logs/
  zic-support:
    container_name: zic-support
    depends_on:
      - zic
    ports:
      - "8082:8082"
    expose:
      - 8082
    restart: always
    environment:
      - ASPNETCORE_URLS=http://+:8082
      - LOG_PATH=/logs/
    volumes:
      - /opt/zerto/zic/logs/:/logs/
  zic-za-reporter:
    container_name: zic-za-reporter
    depends_on:
      - zic
    restart: always
    environment:
      - LOG_PATH=/logs/
      - ZIC_IP_ADDR="${ZIC_IP}"
    volumes:
      - /opt/zerto/zic/logs/:/logs/
    secrets:
      - za_hashed_license
      - zkeycloack_client_id
      - zkeycloack_private_key

secrets:
  za_hashed_license:
    file: /usr/bin/secrets/zerto/zic/za_hashed_license
  zkeycloack_client_id:
    file: /usr/bin/secrets/zerto/zlinux/zerto-domain-cli-client-id
  zkeycloack_private_key:
    file: /usr/bin/secrets/zerto/zlinux/zerto-domain-cli-private-key.pem
    
networks:
  default:
    external:
      name: "zerto-net"